# Generated by Django 4.1.4 on 2023-05-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_category_description_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
