# Generated by Django 4.1.4 on 2023-05-31 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_title_auction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 31, 21, 0, 19, 83762, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
