# Generated by Django 4.1.7 on 2023-06-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_auction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="bid_minimum_increase",
            field=models.FloatField(default=5),
        ),
    ]
